/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: (typeof import('./components/layouts/BaseSide.vue'))['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: (typeof import('element-plus/es'))['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox']
    ElCheckboxGroup: (typeof import('element-plus/es'))['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider']
    ElContainer: (typeof import('element-plus/es'))['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: (typeof import('element-plus/es'))['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: (typeof import('element-plus/es'))['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: (typeof import('element-plus/es'))['ElMenuItemGroup']
    ElOption: (typeof import('element-plus/es'))['ElOption']
    ElRadio: (typeof import('element-plus/es'))['ElRadio']
    ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: (typeof import('element-plus/es'))['ElSelect']
    ElSelectV2: (typeof import('element-plus/es'))['ElSelectV2']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimePicker: (typeof import('element-plus/es'))['ElTimePicker']
    ElUpload: (typeof import('element-plus/es'))['ElUpload']
    FileUploadTest: (typeof import('./components/Movie/FileUploadTest.vue'))['default']
    HelloWorld: (typeof import('./components/HelloWorld.vue'))['default']
    InputFindByTitle: (typeof import('./components/Movie/InputFindByTitle.vue'))['default']
    Logos: (typeof import('./components/Logos.vue'))['default']
    MovieConcrete: typeof import('./components/Movie/MovieConcrete.vue')['default']
    MovieForm: typeof import('./components/Movie/MovieForm.vue')['default']
    MovieFormCreate: (typeof import('./components/Movie/MovieFormCreate.vue'))['default']
    MovieInputFind: typeof import('./components/Movie/MovieInputFind.vue')['default']
    MoviesCarousel: typeof import('./components/Movie/MoviesCarousel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestB: (typeof import('./components/Movie/TestB.vue'))['default']
    TestChatGPT: (typeof import('./components/Movie/TestChatGPT.vue'))['default']
    TeTest: (typeof import('./components/TeTest.vue'))['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
